### ISSUE TITLE
Replace gulp with npm scripts.

### ISSUE THREAD

**Issue by SimonMckeon** [thisisbliss/bliss-go#8]
There is nothing in the gulp file that can't be done with npm scripts - removing a dependency and a file in the root directory.
---

Using NPM scripts will remove a lot of the nice gulp colours and formatting, I'll leave it up to the team to decide which is more important, one less global dependency, or nice formatting. Feel free to close the issue if we decide to stick with Gulp.

**Comment by thebrainroom** [comment]
Nice easy to read formatting every time. I'm sure we'll revisit this at some point.
