### ISSUE TITLE
Use a sass map to organise z-index.  

### ISSUE THREAD

**Issue by spacelab2** [thisisbliss/bliss-go#9]

**Comment by spacelab2** [comment]
Inspired by this article on CSS tricks https://css-tricks.com/handling-z-index/ using a Sass map as a way to organise the z-index on sites.

**Comment by SimonMckeon** [comment]
I like the idea, but I'm struggling to see why the added complexity of using a map and mixin/function would be better than simply using a namespaced variable such as $z-front or $z-back.

**Comment by spacelab2** [comment]
Thanks, Simon. Yes, I see what you mean, perhaps it is a bit over the top using the map and function when we could just as easily set variables. 

I've used the map as I like the idea of gathering all of the z-indexes in one place and adding a warning to let you know if it hasn't worked which I thought might be useful. The map keys could be updated depending on the project you were working on. For example, rather than 'layer-one', 'layer-two' they could be named depending on where they are used in the project for example, header, modal etc. You will then know how many layers are used and it will hopefully help to keep track of them.

**Comment by SimonMckeon** [comment]
After looking at your pull request. I can see the benefit of using a map, especially with the use of a warning. It gets my vote.

**Comment by SimonMckeon** [comment]
I'd like to see this in the 8.x branch, too. I'm happy to submit a PR, unless @spacelab2 would like to go ahead and do it.

**Comment by spacelab2** [comment]
Thanks Simon - I've submitted a pull request.

**Comment by spacelab2** [comment]
This has now been merged into the 8.x branch.
